CREATE TABLE `assets` (
  `id` int NOT NULL AUTO_INCREMENT,
  `asset_no` varchar(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `category` enum('Human','IT Infrastructure','Service','Digital','Tangible Information','End User','Facility') NOT NULL,
  `asset_type_id` int DEFAULT NULL,
  `description` text,
  `cia_confidentiality` tinyint NOT NULL DEFAULT '1',
  `cia_integrity` tinyint NOT NULL DEFAULT '1',
  `cia_availability` tinyint NOT NULL DEFAULT '1',
  `asset_value` tinyint DEFAULT NULL,
  `classification` enum('High','Medium','Low') DEFAULT NULL,
  `color_code` varchar(20) DEFAULT NULL,
  `cis_benchmark_score` decimal(5,2) DEFAULT NULL,
  `is_cis_compliant` tinyint(1) DEFAULT '1',
  `financial_type` enum('CAPEX','OPEX','None') DEFAULT 'None',
  `po_number` varchar(100) DEFAULT NULL,
  `cost` decimal(12,2) DEFAULT '0.00',
  `net_value` decimal(12,2) DEFAULT '0.00',
  `currency` varchar(10) DEFAULT 'USD',
  `remarks` text,
  `status` enum('Available','In Use','In Maintenance','In Repair','Broken','Retired','Lost') DEFAULT 'Available',
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `location_id` bigint DEFAULT NULL,
  `sub_location_id` bigint DEFAULT NULL,
  `support_document_id` int DEFAULT NULL,
  `asset_owner_user_id` int DEFAULT NULL,
  `asset_owner_designation_id` int DEFAULT NULL,
  `asset_custodian_user_id` int DEFAULT NULL,
  `asset_custodian_designation_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `asset_no` (`asset_no`),
  KEY `created_by` (`created_by`),
  KEY `fk_assets_asset_type_id` (`asset_type_id`),
  KEY `fk_assets_location` (`location_id`),
  KEY `fk_assets_sub_location` (`sub_location_id`),
  KEY `fk_assets_support_document` (`support_document_id`),
  KEY `fk_assets_owner_user` (`asset_owner_user_id`),
  KEY `fk_assets_owner_designation` (`asset_owner_designation_id`),
  KEY `fk_assets_custodian_user` (`asset_custodian_user_id`),
  KEY `fk_assets_custodian_designation` (`asset_custodian_designation_id`),
  CONSTRAINT `assets_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_assets_asset_type_id` FOREIGN KEY (`asset_type_id`) REFERENCES `asset_types` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_custodian_designation` FOREIGN KEY (`asset_custodian_designation_id`) REFERENCES `designations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_custodian_user` FOREIGN KEY (`asset_custodian_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_location` FOREIGN KEY (`location_id`) REFERENCES `locations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_owner_designation` FOREIGN KEY (`asset_owner_designation_id`) REFERENCES `designations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_owner_user` FOREIGN KEY (`asset_owner_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_sub_location` FOREIGN KEY (`sub_location_id`) REFERENCES `sub_locations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_assets_support_document` FOREIGN KEY (`support_document_id`) REFERENCES `documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `assets_chk_1` CHECK ((`cia_confidentiality` between 1 and 3)),
  CONSTRAINT `assets_chk_2` CHECK ((`cia_integrity` between 1 and 3)),
  CONSTRAINT `assets_chk_3` CHECK ((`cia_availability` between 1 and 3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
